AllCops:
  Exclude:
    - db/schema.rb
    - "binstubs/**/*"
    - "bin/**/*"
    - "Gemfile"
    - "*.gemspec"

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Style/Copyright:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - require
    - require_relative
    - context
    - be
    - task
    - desc
    - describe
    - it

Style/SymbolArray:
  Enabled: false
